Repository RHEAGROUP/COMET-Server-Administration-Tool, pull requests merged in 2021-07, with the labels that each got.

#129 #117 Add missing logs
  Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs
  Modules/StressGenerator/Utils/ParameterGenerator.cs
  Modules/StressGenerator/Utils/StressGenerator.cs
  Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
  Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
Labels: CDF, StressGenerator

#131 #128 SAT migration process improvements
  Modules/Common/Events/FlushLogEvent.cs
  Modules/Migration.Tests/MigrationTestFixture.cs
  Modules/Migration/Utils/Migration.cs
  Modules/Migration/ViewModels/MigrationViewModel.cs
  Modules/Migration/Views/Layout.xaml
  Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs
  Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
  Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
  Modules/StressGenerator/Views/Layout.xaml
Labels: CDF, DEHP, Server Admin Tool

#134 CodeSmell S1135 - Update TODO comments
  Modules/Migration/Utils/Migration.cs
  Modules/Syncer/Utils/ThingType.cs
Labels: CDF

#133 CodeSmell CS1998 - This async method lacks 'await' operators
  Modules/Migration.Tests/MigrationTestFixture.cs
Labels: CDF

#132 CodeSmell S1481 - Remove the unused local variable 'zipSession'
  Modules/Migration/Utils/Migration.cs
Labels: CDF

#135 #193 Support for open and read silently(no messagebus)
  Modules/Common/Common.csproj
  Modules/Migration.Tests/Migration.Tests.csproj
  Modules/Migration/Migration.csproj
  Modules/Migration/Utils/Migration.cs
  Modules/StressGenerator.Tests/StressGenerator.Tests.csproj
  Modules/StressGenerator/StressGenerator.csproj
  Modules/Syncer.Tests/Syncer.Tests.csproj
  Modules/Syncer/Syncer.csproj
  SAT.Tests/SAT.Tests.csproj
  SAT/SAT.csproj
Labels: 0.5sp
