Repository RHEAGROUP/COMET-Server-Administration-Tool, pull requests merged in 2021-06, with the labels that each got.

#115 Log iteration count inside the model too
  Modules/Migration/Utils/Migration.cs
Labels: CDF, Server Admin Tool

#118 Reading iteration failed for models that have multiple iterations
  Modules/Migration/Utils/Migration.cs
Labels: CDF, Server Admin Tool

#120 #119 Reactive UI crash
  Modules/Migration/Migration.csproj
  Modules/Migration/Utils/Migration.cs
  SAT/SAT.csproj
Labels: CDF

#122 #121 Autofix ParameterSubscription cardinality errors
  CDP4-SAT.sln.DotSettings
  Modules/Common/Common.csproj
  Modules/Common/ViewModels/PlainObjects/POCOErrorRowViewModel.cs
  Modules/Common/ViewModels/PlainObjects/RuleCheckerErrorRowViewModel.cs
  Modules/Migration.Tests/Migration.Tests.csproj
  Modules/Migration.Tests/PocoCardinalityTestFixture.cs
  Modules/Migration/Migration.csproj
  Modules/Migration/ViewModels/FixCardinalityErrorsDialogViewModel.cs
  Modules/StressGenerator.Tests/StressGenerator.Tests.csproj
  Modules/StressGenerator.Tests/app.config
  Modules/StressGenerator/StressGenerator.csproj
  Modules/Syncer.Tests/Syncer.Tests.csproj
  Modules/Syncer.Tests/app.config
  Modules/Syncer/Syncer.csproj
  SAT.Tests/SAT.Tests.csproj
  SAT.Tests/app.config
  SAT/SAT.csproj
Labels: CDF

#124 #123 Add write retry on failure
  Modules/StressGenerator/StressGenerator.csproj
  Modules/StressGenerator/Utils/IterationGenerator.cs
  Modules/StressGenerator/Utils/StressGenerator.cs
Labels: CDF, StressGenerator

#126 #117 stress generator additional options changes
  Modules/Common/Events/LogEvent.cs
  Modules/Common/ViewModels/BaseModuleViewModel.cs
  Modules/Common/ViewModels/LoginViewModel.cs
  Modules/Migration/Utils/Migration.cs
  Modules/Migration/ViewModels/FixCardinalityErrorsDialogViewModel.cs
  Modules/Migration/ViewModels/MigrationViewModel.cs
  Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs
  Modules/StressGenerator/Utils/EngineeringModelSetupGenerator.cs
  Modules/StressGenerator/Utils/IterationGenerator.cs
  Modules/StressGenerator/Utils/ParameterGenerator.cs
  Modules/StressGenerator/Utils/StressGenerator.cs
  Modules/StressGenerator/Utils/WriteHelper.cs
  Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
  Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
  Modules/StressGenerator/Views/Layout.xaml
Labels: CDF, Server Admin Tool

#127 #81 Unify output messages mechanism
  Modules/Common/ViewModels/BaseModuleViewModel.cs
  Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
  Modules/Syncer/ViewModels/SyncerViewModel.cs
Labels: CDF, Server Admin Tool
